version: '3.7'

services:

  ignite-1:
    container_name: ignite-1
    hostname: ignite-1
    image: apacheignite/ignite:2.7.6
    ports:
      - 47500:47500
      - 47100:47100
    volumes:
      - ./ignite-config.xml:/config/ignite-config.xml
    environment:
      - IGNITE_QUIET=false
      - CONFIG_URI=/config/ignite-config.xml

  ignite-2:
    container_name: ignite-2
    hostname: ignite-2
    image: apacheignite/ignite:2.7.6
    volumes:
      - ./ignite-config.xml:/config/ignite-config.xml
    environment:
      - CONFIG_URI=/config/ignite-config.xml

  ignite-3:
    container_name: ignite-3
    hostname: ignite-3
    image: apacheignite/ignite:2.7.6
    volumes:
      - ./ignite-config.xml:/config/ignite-config.xml
    environment:
      - CONFIG_URI=/config/ignite-config.xml

  app:
    hostname: app
    depends_on:
      - ignite-1
      - ignite-2
      - ignite-3
    build:
      context: ""
      dockerfile: Dockerfile
